
package dmit2015.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HumanResourceXmlWebService", targetNamespace = "http://localhost/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HumanResourceXmlWebService {


    /**
     * 
     * @param times
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "LuckyNumber", targetNamespace = "")
    @RequestWrapper(localName = "sortLuckyNumber", targetNamespace = "http://localhost/", className = "dmit2015.soap.SortLuckyNumber")
    @ResponseWrapper(localName = "sortLuckyNumberResponse", targetNamespace = "http://localhost/", className = "dmit2015.soap.SortLuckyNumberResponse")
    public String sortLuckyNumber(
        @WebParam(name = "times", targetNamespace = "")
        int times);

    /**
     * 
     * @return
     *     returns java.util.List<dmit2015.soap.Job>
     */
    @WebMethod
    @WebResult(name = "allJobs", targetNamespace = "")
    @RequestWrapper(localName = "findAllJobs", targetNamespace = "http://localhost/", className = "dmit2015.soap.FindAllJobs")
    @ResponseWrapper(localName = "findAllJobsResponse", targetNamespace = "http://localhost/", className = "dmit2015.soap.FindAllJobsResponse")
    public List<Job> findAllJobs();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "luckyLottoNumber", targetNamespace = "http://localhost/", className = "dmit2015.soap.LuckyLottoNumber")
    @ResponseWrapper(localName = "luckyLottoNumberResponse", targetNamespace = "http://localhost/", className = "dmit2015.soap.LuckyLottoNumberResponse")
    public int luckyLottoNumber();

    /**
     * 
     * @param jobid
     * @return
     *     returns dmit2015.soap.Job
     */
    @WebMethod
    @WebResult(name = "findOneJob", targetNamespace = "")
    @RequestWrapper(localName = "findOneJob", targetNamespace = "http://localhost/", className = "dmit2015.soap.FindOneJob")
    @ResponseWrapper(localName = "findOneJobResponse", targetNamespace = "http://localhost/", className = "dmit2015.soap.FindOneJobResponse")
    public Job findOneJob(
        @WebParam(name = "jobid", targetNamespace = "")
        String jobid);

}
